# Use root/example as user/password credentials
version: '3.1'

services:
  web:
    image: tp33/django
    ports:
      - 80:8000
    volumes:
      - ./web/:/app
    command: bash -c " pip install --upgrade -r requirements.txt
      && python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
