# Use root/example as user/password credentials
version: '3.1'

services:
  web:
    build: .
    ports:
      - 80:8000
    volumes:
      - ./:/app
    command: bash -c " pip install --upgrade -r requirements.txt
      && python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runmodwsgi --reload-on-changes"
